plugins {
    id 'java'
}

group = 'ru.t1.authomatization'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform {
        includeTags 'fast', 'parametrized', 'edge'
        excludeTags 'slow', 'integration'
    }
    testLogging {
        events "passed", "skipped", "failed"
    }
}

task runTests(type: Test) {
    dependsOn test
    doLast {
        println "Test run is over"
    }
}

task runAll(dependsOn: runTests) {
    description = 'Runs all tests and prints completion message'
}
